use std::{
    collections::BTreeMap,
    fmt,
    time::{SystemTime, UNIX_EPOCH},
};

use serde::{Deserialize, Deserializer, Serialize, de};
use serde_json::Value;

/// Canonical role discriminator used by the session protocol.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SessionRole {
    User,
    Agent,
}

/// Text output emitted inside a session envelope.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionTextEvent {
    /// Human-readable text content.
    pub text: String,
    /// Optional marker for model thinking or hidden reasoning text.
    #[serde(
        default,
        with = "crate::serde_helpers::strict_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub thinking: Option<bool>,
}

impl SessionTextEvent {
    pub fn new(text: impl Into<String>) -> Self {
        Self {
            text: text.into(),
            thinking: None,
        }
    }
}

/// Service status text emitted by the agent runtime.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionServiceEvent {
    /// Service message text shown to the user.
    pub text: String,
}

/// Tool invocation start event emitted before a tool call completes.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionToolCallStartEvent {
    /// Stable tool call identifier.
    pub call: String,
    /// Runtime tool name.
    pub name: String,
    /// Human-readable tool title.
    pub title: String,
    /// Tool description displayed by clients.
    pub description: String,
    /// JSON object containing tool arguments.
    pub args: BTreeMap<String, Value>,
}

/// Tool invocation completion event.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionToolCallEndEvent {
    /// Tool call identifier matching the corresponding start event.
    pub call: String,
}

/// Optional image metadata attached to a file event.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionFileImage {
    /// Image width in pixels.
    pub width: u64,
    /// Image height in pixels.
    pub height: u64,
    /// Thumbhash preview generated by Happy clients.
    pub thumbhash: String,
}

/// File attachment event emitted inside the session protocol.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionFileEvent {
    /// File reference token used to fetch the attachment.
    pub r#ref: String,
    /// Display name shown to users.
    pub name: String,
    /// File size in bytes.
    pub size: u64,
    /// Optional MIME type when known.
    #[serde(
        rename = "mimeType",
        default,
        with = "crate::serde_helpers::strict_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mime_type: Option<String>,
    /// Optional image metadata for image attachments.
    #[serde(
        default,
        with = "crate::serde_helpers::strict_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub image: Option<SessionFileImage>,
}

/// Marker event emitted when a turn begins.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionTurnStartEvent {}

/// Session start event emitted for agent or subagent runs.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionStartEvent {
    /// Optional title describing the started agent or task.
    #[serde(
        default,
        with = "crate::serde_helpers::strict_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub title: Option<String>,
}

/// Completion status for a session turn.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum SessionTurnEndStatus {
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "cancelled")]
    Cancelled,
}

/// Marker event emitted when a turn ends.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionTurnEndEvent {
    /// Final turn status.
    pub status: SessionTurnEndStatus,
}

/// Marker event emitted when an agent or subagent stops.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionStopEvent {}

/// Canonical session event union discriminated by `t`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "t")]
pub enum SessionEvent {
    #[serde(rename = "text")]
    Text {
        #[serde(flatten)]
        event: SessionTextEvent,
    },
    #[serde(rename = "service")]
    Service {
        #[serde(flatten)]
        event: SessionServiceEvent,
    },
    #[serde(rename = "tool-call-start")]
    ToolCallStart {
        #[serde(flatten)]
        event: SessionToolCallStartEvent,
    },
    #[serde(rename = "tool-call-end")]
    ToolCallEnd {
        #[serde(flatten)]
        event: SessionToolCallEndEvent,
    },
    #[serde(rename = "file")]
    File {
        #[serde(flatten)]
        event: SessionFileEvent,
    },
    #[serde(rename = "turn-start")]
    TurnStart {
        #[serde(flatten)]
        event: SessionTurnStartEvent,
    },
    #[serde(rename = "start")]
    Start {
        #[serde(flatten)]
        event: SessionStartEvent,
    },
    #[serde(rename = "turn-end")]
    TurnEnd {
        #[serde(flatten)]
        event: SessionTurnEndEvent,
    },
    #[serde(rename = "stop")]
    Stop {
        #[serde(flatten)]
        event: SessionStopEvent,
    },
}

impl SessionEvent {
    pub fn kind(&self) -> &'static str {
        match self {
            Self::Text { .. } => "text",
            Self::Service { .. } => "service",
            Self::ToolCallStart { .. } => "tool-call-start",
            Self::ToolCallEnd { .. } => "tool-call-end",
            Self::File { .. } => "file",
            Self::TurnStart { .. } => "turn-start",
            Self::Start { .. } => "start",
            Self::TurnEnd { .. } => "turn-end",
            Self::Stop { .. } => "stop",
        }
    }
}

macro_rules! impl_event_from {
    ($ty:ty, $variant:ident) => {
        impl From<$ty> for SessionEvent {
            fn from(event: $ty) -> Self {
                Self::$variant { event }
            }
        }
    };
}

impl_event_from!(SessionTextEvent, Text);
impl_event_from!(SessionServiceEvent, Service);
impl_event_from!(SessionToolCallStartEvent, ToolCallStart);
impl_event_from!(SessionToolCallEndEvent, ToolCallEnd);
impl_event_from!(SessionFileEvent, File);
impl_event_from!(SessionTurnStartEvent, TurnStart);
impl_event_from!(SessionStartEvent, Start);
impl_event_from!(SessionTurnEndEvent, TurnEnd);
impl_event_from!(SessionStopEvent, Stop);

/// Canonical session envelope stored inside encrypted session content.
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct SessionEnvelope {
    /// Globally unique envelope identifier.
    pub id: String,
    /// Millisecond timestamp from the emitting runtime.
    pub time: u64,
    /// Message role for the event payload.
    pub role: SessionRole,
    /// Optional turn identifier for turn-scoped agent output.
    #[serde(
        default,
        with = "crate::serde_helpers::strict_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub turn: Option<String>,
    /// Optional subagent identifier; when present it must be a cuid2 string.
    #[serde(
        default,
        with = "crate::serde_helpers::strict_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub subagent: Option<String>,
    /// Event payload discriminated by `t`.
    pub ev: SessionEvent,
}

impl SessionEnvelope {
    pub fn validate(&self) -> Result<(), SessionEnvelopeValidationError> {
        if let Some(subagent) = &self.subagent
            && !cuid2::is_cuid2(subagent)
        {
            return Err(SessionEnvelopeValidationError::InvalidSubagent(
                subagent.clone(),
            ));
        }

        if matches!(
            self.ev,
            SessionEvent::Service { .. } | SessionEvent::Start { .. } | SessionEvent::Stop { .. }
        ) && self.role != SessionRole::Agent
        {
            return Err(SessionEnvelopeValidationError::InvalidRoleForEvent {
                event: self.ev.kind(),
                expected: SessionRole::Agent,
                actual: self.role,
            });
        }

        Ok(())
    }
}

impl<'de> Deserialize<'de> for SessionEnvelope {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct Wire {
            id: String,
            time: u64,
            role: SessionRole,
            #[serde(default, with = "crate::serde_helpers::strict_option")]
            turn: Option<String>,
            #[serde(default, with = "crate::serde_helpers::strict_option")]
            subagent: Option<String>,
            ev: SessionEvent,
        }

        let wire = Wire::deserialize(deserializer)?;
        let envelope = Self {
            id: wire.id,
            time: wire.time,
            role: wire.role,
            turn: wire.turn,
            subagent: wire.subagent,
            ev: wire.ev,
        };
        envelope.validate().map_err(de::Error::custom)?;
        Ok(envelope)
    }
}

/// Optional overrides used by `create_envelope`.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct CreateEnvelopeOptions {
    /// Explicit envelope id; defaults to a generated cuid2 when omitted.
    pub id: Option<String>,
    /// Explicit timestamp in milliseconds; defaults to current system time when omitted.
    pub time: Option<u64>,
    /// Optional turn identifier; empty strings are treated as omitted for Happy parity.
    pub turn: Option<String>,
    /// Optional subagent identifier; empty strings are treated as omitted for Happy parity.
    pub subagent: Option<String>,
}

/// Constructs a validated session envelope using Happy-compatible defaults.
pub fn create_envelope(
    role: SessionRole,
    ev: SessionEvent,
    opts: CreateEnvelopeOptions,
) -> Result<SessionEnvelope, SessionEnvelopeValidationError> {
    let envelope = SessionEnvelope {
        id: opts.id.unwrap_or_else(cuid2::create_id),
        time: opts.time.unwrap_or_else(current_time_millis),
        role,
        turn: omit_empty_string(opts.turn),
        subagent: omit_empty_string(opts.subagent),
        ev,
    };
    envelope.validate()?;
    Ok(envelope)
}

/// Validation failures surfaced by `SessionEnvelope::validate` and `create_envelope`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SessionEnvelopeValidationError {
    InvalidRoleForEvent {
        event: &'static str,
        expected: SessionRole,
        actual: SessionRole,
    },
    InvalidSubagent(String),
}

impl fmt::Display for SessionEnvelopeValidationError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidRoleForEvent {
                event,
                expected,
                actual,
            } => write!(
                f,
                "{event} events must use role \"{}\", got \"{}\"",
                role_name(*expected),
                role_name(*actual)
            ),
            Self::InvalidSubagent(value) => {
                write!(f, "subagent must be a cuid2 value, got \"{value}\"")
            }
        }
    }
}

impl std::error::Error for SessionEnvelopeValidationError {}

fn omit_empty_string(value: Option<String>) -> Option<String> {
    value.and_then(|value| if value.is_empty() { None } else { Some(value) })
}

fn current_time_millis() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system time should be after the unix epoch")
        .as_millis() as u64
}

fn role_name(role: SessionRole) -> &'static str {
    match role {
        SessionRole::User => "user",
        SessionRole::Agent => "agent",
    }
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::{
        CreateEnvelopeOptions, SessionEnvelope, SessionEvent, SessionFileEvent, SessionFileImage,
        SessionRole, SessionServiceEvent, SessionStartEvent, SessionStopEvent, SessionTextEvent,
        SessionToolCallEndEvent, SessionToolCallStartEvent, SessionTurnEndEvent,
        SessionTurnEndStatus, SessionTurnStartEvent, create_envelope,
    };

    #[test]
    fn supported_event_types_round_trip() {
        let events = vec![
            SessionEvent::from(SessionTextEvent::new("hello")),
            SessionEvent::from(SessionTextEvent {
                text: "thinking".into(),
                thinking: Some(true),
            }),
            SessionEvent::from(SessionServiceEvent {
                text: "**Service:** restarting MCP bridge".into(),
            }),
            SessionEvent::from(SessionToolCallStartEvent {
                call: "call-1".into(),
                name: "CodexBash".into(),
                title: "Run `ls`".into(),
                description: "Run `ls -la` in the repo root".into(),
                args: [("command".into(), json!("ls -la"))].into_iter().collect(),
            }),
            SessionEvent::from(SessionToolCallEndEvent {
                call: "call-1".into(),
            }),
            SessionEvent::from(SessionFileEvent {
                r#ref: "upload-1".into(),
                name: "report.txt".into(),
                size: 1024,
                mime_type: Some("text/plain".into()),
                image: None,
            }),
            SessionEvent::from(SessionFileEvent {
                r#ref: "upload-2".into(),
                name: "image.png".into(),
                size: 2048,
                mime_type: Some("image/png".into()),
                image: Some(SessionFileImage {
                    thumbhash: "abc".into(),
                    width: 100,
                    height: 80,
                }),
            }),
            SessionEvent::from(SessionTurnStartEvent::default()),
            SessionEvent::from(SessionStartEvent {
                title: Some("Research agent".into()),
            }),
            SessionEvent::from(SessionTurnEndEvent {
                status: SessionTurnEndStatus::Completed,
            }),
            SessionEvent::from(SessionStopEvent::default()),
        ];

        for event in events {
            let value = serde_json::to_value(&event).unwrap();
            let parsed: SessionEvent = serde_json::from_value(value).unwrap();
            assert_eq!(parsed, event);
        }
    }

    #[test]
    fn malformed_events_are_rejected() {
        let bad_events = [
            json!({ "t": "tool-call-start", "call": "1" }),
            json!({ "t": "file", "ref": "x", "name": "x" }),
            json!({ "t": "file", "ref": "x", "name": "x", "size": 1, "image": { "width": 10, "height": 10 } }),
            json!({ "t": "turn-end" }),
            json!({ "t": "turn-end", "status": "canceled" }),
            json!({ "t": "start", "title": 1 }),
            json!({ "t": "service" }),
            json!({ "t": "not-real" }),
        ];

        for bad_event in bad_events {
            assert!(serde_json::from_value::<SessionEvent>(bad_event).is_err());
        }
    }

    #[test]
    fn envelopes_with_turn_and_subagent_validate() {
        let subagent = cuid2::create_id();
        let envelope = serde_json::from_value::<SessionEnvelope>(json!({
            "id": "msg-1",
            "time": 1234,
            "role": "agent",
            "turn": "turn-1",
            "subagent": subagent,
            "ev": {
                "t": "text",
                "text": "hello",
            }
        }))
        .unwrap();

        assert_eq!(envelope.turn.as_deref(), Some("turn-1"));
        assert_eq!(envelope.subagent.as_deref().unwrap().len(), 24);
    }

    #[test]
    fn service_start_and_stop_require_agent_role() {
        let service = serde_json::from_value::<SessionEnvelope>(json!({
            "id": "msg-2",
            "time": 1,
            "role": "user",
            "ev": {
                "t": "service",
                "text": "internal event",
            }
        }))
        .unwrap_err();
        let start = serde_json::from_value::<SessionEnvelope>(json!({
            "id": "msg-3",
            "time": 1,
            "role": "user",
            "ev": {
                "t": "start",
                "title": "Research agent",
            }
        }))
        .unwrap_err();
        let stop = serde_json::from_value::<SessionEnvelope>(json!({
            "id": "msg-4",
            "time": 1,
            "role": "user",
            "ev": {
                "t": "stop"
            }
        }))
        .unwrap_err();

        assert!(service.to_string().contains("service events must use role"));
        assert!(start.to_string().contains("start events must use role"));
        assert!(stop.to_string().contains("stop events must use role"));
    }

    #[test]
    fn non_cuid_subagent_is_rejected() {
        let error = serde_json::from_value::<SessionEnvelope>(json!({
            "id": "msg-5",
            "time": 1,
            "role": "agent",
            "turn": "turn-1",
            "subagent": "provider-tool-id",
            "ev": {
                "t": "text",
                "text": "hello",
            }
        }))
        .unwrap_err();

        assert!(error.to_string().contains("subagent must be a cuid2 value"));
    }

    #[test]
    fn invalid_null_optional_only_fields_are_rejected() {
        let invalid_events = [
            json!({ "t": "text", "text": "hello", "thinking": null }),
            json!({ "t": "file", "ref": "upload-1", "name": "report.txt", "size": 1, "mimeType": null }),
            json!({
                "t": "file",
                "ref": "upload-1",
                "name": "report.txt",
                "size": 1,
                "image": null,
            }),
            json!({ "t": "start", "title": null }),
        ];

        for invalid_event in invalid_events {
            assert!(serde_json::from_value::<SessionEvent>(invalid_event).is_err());
        }

        let invalid_envelopes = [
            json!({
                "id": "msg-6",
                "time": 1,
                "role": "agent",
                "turn": null,
                "ev": {
                    "t": "text",
                    "text": "hello",
                }
            }),
            json!({
                "id": "msg-7",
                "time": 1,
                "role": "agent",
                "subagent": null,
                "ev": {
                    "t": "text",
                    "text": "hello",
                }
            }),
        ];

        for invalid_envelope in invalid_envelopes {
            assert!(serde_json::from_value::<SessionEnvelope>(invalid_envelope).is_err());
        }
    }

    #[test]
    fn create_envelope_generates_defaults() {
        let envelope = create_envelope(
            SessionRole::Agent,
            SessionEvent::from(SessionTurnStartEvent::default()),
            CreateEnvelopeOptions::default(),
        )
        .unwrap();

        assert!(cuid2::is_cuid2(&envelope.id));
        assert!(envelope.time > 0);
        assert_eq!(envelope.role, SessionRole::Agent);
        assert!(matches!(envelope.ev, SessionEvent::TurnStart { .. }));
    }

    #[test]
    fn create_envelope_respects_explicit_options() {
        let subagent = cuid2::create_id();
        let envelope = create_envelope(
            SessionRole::Agent,
            SessionEvent::from(SessionToolCallEndEvent {
                call: "call-1".into(),
            }),
            CreateEnvelopeOptions {
                id: Some("fixed-id".into()),
                time: Some(12345),
                turn: Some("turn-1".into()),
                subagent: Some(subagent.clone()),
            },
        )
        .unwrap();

        assert_eq!(envelope.id, "fixed-id");
        assert_eq!(envelope.time, 12345);
        assert_eq!(envelope.turn.as_deref(), Some("turn-1"));
        assert_eq!(envelope.subagent.as_deref(), Some(subagent.as_str()));
    }

    #[test]
    fn create_envelope_validates_role_event_compatibility() {
        let error = create_envelope(
            SessionRole::User,
            SessionEvent::from(SessionServiceEvent {
                text: "internal event".into(),
            }),
            CreateEnvelopeOptions::default(),
        )
        .unwrap_err();

        assert!(error.to_string().contains("service events must use role"));
    }

    #[test]
    fn create_envelope_omits_empty_turn_and_subagent() {
        let envelope = create_envelope(
            SessionRole::Agent,
            SessionEvent::from(SessionTurnStartEvent::default()),
            CreateEnvelopeOptions {
                turn: Some(String::new()),
                subagent: Some(String::new()),
                ..CreateEnvelopeOptions::default()
            },
        )
        .unwrap();

        assert_eq!(envelope.turn, None);
        assert_eq!(envelope.subagent, None);

        let value = serde_json::to_value(envelope).unwrap();
        assert!(value.get("turn").is_none());
        assert!(value.get("subagent").is_none());
    }
}
